name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: "0"

    - name: Setup Node@14
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.x

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.x

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'

    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0.9.7
      with:
        useConfigFile: true
        configFilePath: GitVersion.yml
        
    - name: Install dependencies
      run: dotnet restore

    - name: NPM install
      run: npm install
      working-directory: SpeedWagon.Client
    
    - name: Gulp
      run: gulp build
      working-directory: SpeedWagon.Client

    - name: Replace Tokens
      uses: cschleiden/replace-tokens@v1
      with:
        files: '["**/*.nuspec"]'
      env:
        GITVERSION_FULLSEMVER: ${{ env.GITVERSION_FULLSEMVER }}

    - name: Remove Sln
      run: dotnet sln remove SpeedWagon.Client/SpeedWagon.Client.njsproj
        
    - name: Build
      run: dotnet build --configuration Release --no-restore /p:Version="${{ env.GITVERSION_FULLSEMVER }}"

    - name: Pack Web.UI
      run: dotnet pack --configuration Release --no-restore /p:Version="${{ env.GITVERSION_FULLSEMVER }}"
        
    - name: Pack Web
      run: dotnet pack -p:NuspecFile=SpeedWagon.Web.nuspec -p:Configuration=Release -o .\
      working-directory: SpeedWagon.Web

    - name: Pack Runtime
      run: dotnet pack -p:NuspecFile=SpeedWagon.Runtime.nuspec -p:Configuration=Release -o .\
      working-directory: SpeedWagon.Runtime
      
    - name: Pack Blog Sample
      run: dotnet pack -p:NuspecFile=SpeedWagon.Sample.Blog.nuspec -p:Configuration=Release -o .\
      working-directory: SpeedWagon.Web.UI

    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: dotnet publish
      run: |
        dotnet publish -c Release -o speedwagonapp

    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v1
      with: 
        app-name: speedwagon-demo-site # Replace with your app name
        publish-profile: ${{ secrets.azureWebAppPublishProfile }}
        package: './speedwagonapp'

    - name: Publish Web Nuget Package
      env:
        NUGET_APIKEY: ${{ secrets.NUGET_APIKEY }}
      run: nuget push *.nupkg -Source https://api.nuget.org/v3/index.json -ApiKey "${{ env.NUGET_APIKEY }}"
      working-directory: SpeedWagon.Web  

    - name: Publish Runtime Nuget Package
      env:
        NUGET_APIKEY: ${{ secrets.NUGET_APIKEY }}
      run: nuget push *.nupkg -Source https://api.nuget.org/v3/index.json -ApiKey "${{ env.NUGET_APIKEY }}"
      working-directory: SpeedWagon.Runtime  

    - name: Publish Blog Sample Nuget Package
      env:
        NUGET_APIKEY: ${{ secrets.NUGET_APIKEY }}
      run: nuget push *.nupkg -Source https://api.nuget.org/v3/index.json -ApiKey "${{ env.NUGET_APIKEY }}"
      working-directory: SpeedWagon.Web.UI  