name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: "0"

    - name: Setup Node@14
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.x

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'

    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0.9.7

    - name: Install dependencies
      run: dotnet restore

    - name: NPM install
      run: npm install
      working-directory: SpeedWagon.Web.UI

    - name: Gulp
      run: gulp build
      working-directory: SpeedWagon.Web.UI

    - name: Build
      run: dotnet build --configuration Release --no-restore /p:Version=${$GITVERSION_SEMVER}

    - name: Build
      run: dotnet pack --configuration Release --no-restore /p:Version=${$GITVERSION_SEMVER}
        
    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: dotnet publish
      run: |
        dotnet publish -c Release -o speedwagonapp

    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v1
      with: 
        app-name: speedwagon-demo-site # Replace with your app name
        publish-profile: ${{ secrets.azureWebAppPublishProfile }}
        package: './speedwagonapp'
