name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node@14
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.x

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: NPM install
      run: npm install
      working-directory: SpeedWagon.Web.UI

    - name: Gulp
      run: gulp build
      working-directory: SpeedWagon.Web.UI

    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: dotnet publish
      run: |
        dotnet publish -c Release -o speedwagonapp
